### ISSUE TITLE
cant connect to office 365

### ISSUE THREAD

**Issue by mohsin111** [microsoftgraph/android-java-connect-rest-sample#20]
I have add My Application Client ID and Redirect URI,But When I connect to Office 365.It Show Me Error cant connect to office 365

**Comment by Ricalo** [comment]
Hi @mohsin111,

Could you provide more detail?

* Do you get prompted for credentials?
If so, do you get to a page like this one?
![image](https://cloud.githubusercontent.com/assets/989368/14990676/83ea0c70-1112-11e6-8c14-d681d8446e7e.png)
* Can you provide some repro steps?

Thanks for trying this sample
